version: '3.8'
services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - '3000:443'
      - '80:80'
    networks:
      - app-net
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/log:/var/log/nginx
      - /home/admin/conf/web:/etc/nginx/cert
    restart: always
networks:
  app-net:
    external: true
