version: '3.8'
services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - '80:80'
    networks:
      - app-net
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - /home/admin/conf/web:/
    restart: always

networks:
  app-net:
    external: true
